# Generated by Django 2.2.7 on 2019-12-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=40)),
                ('account_type', models.CharField(choices=[('checking', 'CHECKING'), ('savings', 'SAVINGS'), ('credit', 'CREDIT')], default=('checking', 'CHECKING'), max_length=10)),
                ('account_balance', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('student', 'STUDENT'), ('home', 'HOME'), ('car', 'CAR')], default=('student', 'STUDENT'), max_length=10)),
                ('loan_balance', models.CharField(max_length=12)),
                ('amount_due', models.CharField(max_length=10)),
            ],
        ),
    ]
